modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/immortalmice/FoodPower/issues"

[[mods]]
	modId="foodpower"
	version="${version}"
	displayName="Food Power"
	credits="Pudding, donut, and all sweet things."
	authors="Immortalmice, YenHsinWu"
	description='''Food will give you power.<3'''

[[dependencies.foodpower]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.foodpower]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
